spring.application.name=spring-ai-app
#server.port=8084
# since deployment is done on elastic beanstalk
#server.port=5000

# for ecs deployment
server.port=8083


# this is local db configuration of postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/test_db
#spring.datasource.username=postgres
#spring.datasource.password=root

#for aws rds configuration
#spring.datasource.url=jdbc:postgresql://database-1.cn8u6uuiq0gj.eu-north-1.rds.amazonaws.com:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=root1234

# for ecs config of database
spring.datasource.url=jdbc:postgresql://13.51.150.225:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root1234

# JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Defer datasource initialization to allow schema.sql and data.sql to run first after table creation by jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true 
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# SQL initialization configuration to run schema.sql and data.sql on startup
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.h2.console.enabled=true

# ai configuration
spring.ai.ollama.chat.options.model=granite4:350m