spring.application.name=spring-ai-app
server.port=8084

# this is local db configuration of postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/test_db
spring.datasource.username=postgres
spring.datasource.password=root

# JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Defer datasource initialization to allow schema.sql and data.sql to run first after table creation by jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true 
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# SQL initialization configuration to run schema.sql and data.sql on startup
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.h2.console.enabled=true

# ai configuration
spring.ai.ollama.chat.options.model=granite4:350m